trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'space-bot-docker'

steps:
  - task: Dcoker@2
    displayName: Login to ACR
    inputs:
      command: Login
      conainerRegistry: 'my-acr-service-connection'

  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: ./Dockerfile


  - task: Docker@2
    displayName: Push image to ACR
    inputs:
      command: push
      repository: $(acrLoginServer)/$(imageName)

  - task: AzureCLI@2
    inputs:
    azureSubscription: 'my-azure-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az container delete \
        --name myspacebot-instance \
        --resource-group myResourceGroup \
        --yes

      az container create \
        --resource-group myResourceGroup \
        --name myspacebot-instance \
        --image myregistry.azurecr.io/myspacebot:latest \
        --registry-login-server myregistry.azurecr.io \
        --registry-username $(ACR_USERNAME) \
        --registry-password $(ACR_PASSWORD) \
        --dns-name-label myspacebot-demo123 \
        --ports 80