name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: space-bot

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: yourregistry.azurecr.io
          username: ${{ secrets.SPACEBOTTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.SPACEBOTTEST_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME }} yourregistry.azurecr.io/${{ env.IMAGE_NAME }}
          docker push yourregistry.azurecr.io/${{ env.IMAGE_NAME }}
