name: space-bot for Crc project 2025

on:
  push:
    branches:
      - test

run-name: space-bot for Crc project by @${{ github.actor }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create .env file
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> src/.env
        echo "DB_URL=${{ secrets.DB_URL }}" >> src/.env

    # ✅ Build image LOCALLY first for testing
    - name: Build Docker image (local test)
      run: docker build -t space-bot .

    # ✅ Run container (optional step for local testing)
    - name: Run Docker container with env file
      run: docker run --env-file .env space-bot

    # ✅ Login to your Azure Container Registry
    - name: Azure Container Registry Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # ✅ Build and push image to Azure Container Registry
    - name: Build and push image to ACR
      run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/space-bot:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/space-bot:${{ github.sha }}

    # ✅ Deploy container from ACR to Azure Container Instances
    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/space-bot:${{ github.sha }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: space-bot
        location: 'westeurope'
