name: space-bot for Crc project 2025

on:
  workflow_dispatch:
    inputs:
      build_image:
        description: "Build Docker image?"
        required: false
        default: 'true'
      operation:
        description: "Choose deployment operation"
        required: false
        default: 'Reinstall'
        type: choice
        options:
          - Install
          - Uninstall
          - Reinstall
    branches:
      - test

run-name: space-bot for Crc project by @${{ github.actor }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install test Dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install pytest black
      - name: run pytest
        run: pytest
  build:
    needs: test
    if: ${{ github.event.inputs.build_image == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create .env file
      run: |
        echo "NASA_KEY=${{ secrets.NASA_KEY }}" >> src/.env
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> src/.env
      
    - name: Create in root .env file
      run: |
        echo "NASA_KEY=${{ secrets.NASA_KEY }}" >> .env
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env

    - name: Azure Container Registry Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push image to ACR
      run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/space-bot:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/space-bot:${{ github.sha }}
  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Show selected operation
      run: echo "Selected operation ${{ github.event.inputs.operation }}"
        
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      uses: azure/docker-login@v1
      with: 
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Pull image
      run: docker pull ${{ secrets.REGISTRY_LOGIN_SERVER }}/space-bot:${{ github.sha }}

    - name: Stop and remove container (if Uninstall or Reinstall)
      if: ${{ github.event.inputs.operation == 'Uninstall' || github.event.inputs.operation == 'Reinstall' }}
      run: |
        az container delete --name space-bot --resource-group ${{ secrets.RESOURCE_GROUP }} --yes

    - name: Run container (if Install or Reinstall)
      if: ${{ github.event.inputs.operation == 'Install' || github.event.inputs.operation == 'Reinstall' }}
      uses: azure/aci-deploy@v1
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/space-bot:${{ github.sha }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: space-bot
        location: 'west europe'


    