name: Build, Push & Deploy Discord Bot

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: space-bot
  REGISTRY: spacebot2025.azurecr.io
  CONTAINER_APP_NAME: space-bot-test      # <- PODMIEN TO
  RESOURCE_GROUP: project-crc-2025          # <- PODMIEN TO

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.SPACEBOTTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.SPACEBOTTEST_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          publish-profile: ${{ secrets.AZURE_CONTAINERAPPS_PUBLISH_PROFILE }}
          container-app-name: ${{ env.CONTAINER_APP_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
