trigger:

  - main
pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'space-bot'

steps:
- task: Docker@2
  displayName: Build an an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile